### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by koujiisan** [koujiisan/VisitAwesomeExperienceJapan#30]

**Comment by koujiisan** [comment]
## 概要

## 実装機能
### MVP
- [x] 会員登録
- [x] ログイン
- [x] コンテンツ投稿
- [x] コンテンツ詳細
- [x] いいね
- [x] コメント
- [x] タグ

### 必要なページ
- [x] トップページ
- [x] ユーザー登録ページ
- [x] ログインページ
- [x] 体験一覧ページ
- [x] 体験詳細ページ
- [x] ユーザープロフィールページ
- [x] ユーザープロフィール設定ページ
- [x] 体験投稿ページ

**Comment by Tsuchiya2** [comment]
![image](https://github.com/koujiisan/VisitAwesomeExperienceJapan/assets/61481161/6e8f40c3-026c-458f-8df8-172443e9c8b8)

projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムを確認いただいて、上記が確認できる状態でのご提出をお願いいたします。

**Comment by koujiisan** [comment]
ご確認ありがとうございます。
Project自体の公開設定とリポジトリの公開設定と間違えていました。
公開に切り替えたので再度ご確認よろしくお願いいたします

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

（より良い改善案：ストーリーポイント1,2になるくらいまで細分化すると、進捗を感じながら開発を進められます＆明確化している箇所とそうでない箇所が浮き彫りになります）
