### ISSUE TITLE
アプリMVPリリース確認依頼

### ISSUE THREAD

**Issue by koujiisan** [koujiisan/VisitAwesomeExperienceJapan#77]
ご確認よろしくお願いいたします。

## 各種情報
サービス名: VisitAwesomeExperienceJapan
サービスURL: https://vaej-9c6e3332b91b.herokuapp.com/

### MVP
- [x] 会員登録
- [x] ログイン
- [x] コンテンツ投稿
- [x] コンテンツ詳細
- [x] いいね
- [x] コメント
- [x] タグ

### 必要なページ
- [x] トップページ
- [x] ユーザー登録ページ
- [x] ログインページ
- [x] 体験一覧ページ
- [x] 体験詳細ページ
- [x] ユーザープロフィールページ
- [x] ユーザープロフィール設定ページ
- [x] 体験投稿ページ

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください
- [x] Topページ   
![](https://i.gyazo.com/071ded779dbe3108a1cff49a1431da8d.png)     
説明文を記入    
スクロールすると「ログイン」「ユーザー登録」へのボタン表示    
![](https://i.gyazo.com/44c7e7dafffba76263e812cd6da0764f.png)   

- [x] ユーザー登録ページ    
![](https://i.gyazo.com/76d071d3f1c176b7ff9cb9a75eb11a04.png)   
- [x] ログインページ   
![](https://i.gyazo.com/d0dfe0b212094cf93e88cf0b01b15cf9.png)   

- [x] 体験一覧ページ    
![](https://i.gyazo.com/abbfd9e1002038dd8c0a23157e93b809.png)   

- [x] 体験詳細ページ    
![](https://gyazo.com/e11c46a0ad93156f2f6e7f080290a9b3.png)

- [x] ユーザープロフィールページ
![](https://gyazo.com/61eb7c0435dd432755b7b8a253217c60.png)

- [x] ユーザープロフィール設定ページ
![](https://gyazo.com/2d15abe3b878d76882224b892b8010bb.png)

- [x] 体験投稿ページ    
![](https://gyazo.com/114181d86b5559cf1600b4bcc00b817a.png)

## READMEレビュー時から変更した機能
追加機能
- [x] 体験編集ページ    
![](https://gyazo.com/c7f81a1c25ce8c5d88f157d1282c3a99.png)

- [x] ユーザー情報編集ページ
![](https://gyazo.com/c105422cda23ae42e1912048e6fe031d.png)

変更機能    
- [x] コメント機能    
![](https://gyazo.com/1a9f2a9d820d663916b1856ed1b6c6a7.png)

コメント機能はモーダルで表示しようと思いましたが
投稿の下部に表示してスクロールして
その場で投稿するように変更しました。

## サービスイメージがわかるようなスクリーンショット等
管理画面などは作成していません。

なお画面レイアウトは全てモバイルファーストで
スマートフォン画面に適したレイアウトになっています。
レスポンシブ対応はMVPリリース後実施予定です。

画像投稿は投稿できますが、MVPリリースまでに画像サーバーとの連携を考えていませんでしたので
MVPリリース後画像サーバーとの連携を検討します。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
